# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chioces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
