# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170428_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='side',
            options={},
        ),
        migrations.RemoveField(
            model_name='side',
            name='category',
        ),
        migrations.RemoveField(
            model_name='side',
            name='content',
        ),
        migrations.RemoveField(
            model_name='side',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='side',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='side',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='side',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
