# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20170428_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='side',
            name='tel',
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='side',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='side',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
