# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20170428_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.AddField(
            model_name='side',
            name='price',
            field=models.IntegerField(default=0, verbose_name='\u8def\u8d39'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u4fe1\u606f\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u4fe1\u606f\u53d1\u5e03\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(null=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tel',
            field=models.IntegerField(default=0, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='side',
            name='address',
            field=models.CharField(max_length=100, verbose_name='\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='side',
            name='pub_time',
            field=models.DateTimeField(null=True, verbose_name='\u51fa\u53d1\u65f6\u95f4'),
        ),
    ]
